name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust PHP version if needed

      - name: Install dependencies (if any)
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-progress --no-suggest --prefer-dist
          fi

      - name: Run PHP scripts
        run: php index.php  # Replace 'script.php' with your actual file

      - name: Run tests (if applicable)
        run: |
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit
          else
            echo "No tests found, skipping..."
          fi
